config/routes.rb
Rails.application.routes.draw do
  resources :mushrooms, only: [:index]

  root 'mushrooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  self.table_name = 'attributes'
end

app/models/mushroom.rb
class Mushroom < ApplicationRecord
  has_many :mushroom_attributes
  has_many :attribute_items, through: :mushroom_attributes, table_name: 'attributes'

  def self.set_filters(filters)
    relation = Mushroom.all

    active_filters = filters.select { |_key, value| value.present?}

    join_index = 0
    active_filters.inject(Mushroom.all) do |relation, (attribute_name, value)|
      join_name = "join_#{join_index += 1}"
      attribute = Attribute.find_by!(name: attribute_name)
      relation
        .joins("INNER JOIN mushroom_attributes as #{join_name} on #{join_name}.mushroom_id = mushrooms.id")
        .where(join_name => {attribute_item_id: attribute.id, value: value})
    end
  end
end

app/models/mushroom_attribute.rb
class MushroomAttribute < ApplicationRecord
  belongs_to :mushroom
  belongs_to :attribute_item, class_name: :Attribute
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mushrooms_controller.rb
class MushroomsController < ApplicationController
  def index
    @mushrooms =
      if params['filters']
        Mushroom.set_filters(params.require(:filters).permit!.to_hash)
      else
        Mushroom.all
      end

    @filters =
      Attribute.all.inject({}) do |acc, attribute|
        acc[attribute.name] = (attribute.allowed_values || []).split(',')
        acc
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mushroom_helper.rb
module MushroomHelper
  def selected_value(attribute_name)
    return nil unless params['filters']

    params['filters'][attribute_name]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mushrooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/mushrooms/_mushroom.html.slim
tr
  td= mushroom.name

app/views/mushrooms/index.html.slim
#mushrooms_index
  h1 Mushrooms

  h3 Filter
  = form_tag('/',  method: :get, id: 'filtering')
    - @filters.each do |name, options|
      .form-group
        label= name
        = select_tag "filters[#{name}]", options_for_select(options, selected_value(name)), include_blank: true

    = submit_tag 'Apply filters', class: 'btn btn-success'

    br/

    = link_to "Reset filters", mushrooms_path

  table#mushrooms
    thead
      tr
        td Name
    tbody
      = render @mushrooms